@startuml
title Sequence Diagram: EditCommand

participant ":EditCommand" as EC
participant ":WorkoutList" as WL

[-> EC : execute(workouts, ui)
activate EC

alt response contains " e/"
    ref over EC, WL : handleEditExercise(workouts, ui)\n[See EditCommand (Exercise)]
else response does not contain " e/"
    ref over EC, WL : handleEditWorkout(workouts, ui)\n[See EditCommand (Workout)]
end

deactivate EC
@enduml
